<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.5.57" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>02_clean</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<!-- htmldependencies:E3FAD763 -->


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">02_clean</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>WHO 2025 data on Tuberculosis (TB).</p>
<p>In this script, we will be working with the data cleaning.</p>
<p>For that purpose, it can be a great advantage to first understand our data. So this script will also contain a bit about data exploration.</p>
<hr />
<section id="loading-relevant-libraries" class="level1">
<h1><strong>Loading relevant libraries:</strong></h1>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co">#No tidyverse, no R course~</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Access to the function for loading the datasets and to save them</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;99_proj_func.R&quot;</span>)</span></code></pre></div>
</div>
<hr />
</section>
<section id="loading-data" class="level1">
<h1><strong>Loading data:</strong></h1>
<p><strong>WHO TB incidence estimates disaggregated by age group, sex and risk factor [&gt;0.5Mb]:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading age and sex and risk group data (2024 only): </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>data_file   <span class="ot">&lt;-</span> <span class="st">&quot;01_load_TB_age_sex.tsv&quot;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> <span class="fu">load_data</span>(data_file)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading ../data/01_load_TB_age_sex.tsv from local file…</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Display the data: </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,031 × 13
   country     iso2  iso3  iso_numeric  year measure unit  age_group sex  
   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;
 1 Afghanistan AF    AFG   004          2024 inc     num   0-14      a    
 2 Afghanistan AF    AFG   004          2024 inc     num   0-14      f    
 3 Afghanistan AF    AFG   004          2024 inc     num   0-14      m    
 4 Afghanistan AF    AFG   004          2024 inc     num   0-4       a    
 5 Afghanistan AF    AFG   004          2024 inc     num   0-4       f    
 6 Afghanistan AF    AFG   004          2024 inc     num   0-4       m    
 7 Afghanistan AF    AFG   004          2024 inc     num   10-14     a    
 8 Afghanistan AF    AFG   004          2024 inc     num   10-14     f    
 9 Afghanistan AF    AFG   004          2024 inc     num   10-14     m    
10 Afghanistan AF    AFG   004          2024 inc     num   15-19     a    
# ℹ 9,021 more rows
# ℹ 4 more variables: risk_factor &lt;chr&gt;, best &lt;dbl&gt;, lo &lt;dbl&gt;, hi &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>WHO TB burden estimates [&gt;1Mb]:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading TB burden estimates: </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>data_file   <span class="ot">&lt;-</span> <span class="st">&quot;01_load_TB_burden.tsv&quot;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="ot">&lt;-</span> <span class="fu">load_data</span>(data_file)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading ../data/01_load_TB_burden.tsv from local file…</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Display the data: </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>TB_burden</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,347 × 50
   country     iso2  iso3  iso_numeric g_whoregion  year e_pop_num e_inc_100k
   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 Afghanistan AF    AFG   004         EMR          2000  20130323        148
 2 Afghanistan AF    AFG   004         EMR          2001  20284311        175
 3 Afghanistan AF    AFG   004         EMR          2002  21378110        197
 4 Afghanistan AF    AFG   004         EMR          2003  22733047        215
 5 Afghanistan AF    AFG   004         EMR          2004  23560660        228
 6 Afghanistan AF    AFG   004         EMR          2005  24404569        237
 7 Afghanistan AF    AFG   004         EMR          2006  25424099        242
 8 Afghanistan AF    AFG   004         EMR          2007  25909852        241
 9 Afghanistan AF    AFG   004         EMR          2008  26482615        235
10 Afghanistan AF    AFG   004         EMR          2009  27466100        229
# ℹ 5,337 more rows
# ℹ 42 more variables: e_inc_100k_lo &lt;dbl&gt;, e_inc_100k_hi &lt;dbl&gt;,
#   e_inc_num &lt;dbl&gt;, e_inc_num_lo &lt;dbl&gt;, e_inc_num_hi &lt;dbl&gt;,
#   e_tbhiv_prct &lt;dbl&gt;, e_tbhiv_prct_lo &lt;lgl&gt;, e_tbhiv_prct_hi &lt;lgl&gt;,
#   e_inc_tbhiv_100k &lt;dbl&gt;, e_inc_tbhiv_100k_lo &lt;dbl&gt;,
#   e_inc_tbhiv_100k_hi &lt;dbl&gt;, e_inc_tbhiv_num &lt;dbl&gt;, e_inc_tbhiv_num_lo &lt;dbl&gt;,
#   e_inc_tbhiv_num_hi &lt;dbl&gt;, e_mort_exc_tbhiv_100k &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p><strong>WHO TB data dictionary:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading the data dictionary: </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>data_file   <span class="ot">&lt;-</span> <span class="st">&quot;01_load_dictionary.tsv&quot;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>TB_dictionary <span class="ot">&lt;-</span> <span class="fu">load_data</span>(data_file)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading ../data/01_load_dictionary.tsv from local file…</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Display the data: </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>TB_dictionary</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 699 × 4
   variable_name   dataset code_list definition                                 
   &lt;chr&gt;           &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;                                      
 1 budget_cpp_dstb Budget  &lt;NA&gt;      Average cost of drugs budgeted per patient…
 2 budget_cpp_mdr  Budget  &lt;NA&gt;      Average cost of drugs budgeted per patient…
 3 budget_cpp_tpt  Budget  &lt;NA&gt;      Average cost of drugs budgeted per patient…
 4 budget_cpp_xdr  Budget  &lt;NA&gt;      Average cost of drugs budgeted per patient…
 5 budget_fld      Budget  &lt;NA&gt;      Budget required for drugs to treat drug-su…
 6 budget_lab      Budget  &lt;NA&gt;      Budget required for laboratory infrastruct…
 7 budget_mdrmgt   Budget  &lt;NA&gt;      Budget required for programme costs to tre…
 8 budget_orsrvy   Budget  &lt;NA&gt;      Budget required for operational research a…
 9 budget_oth      Budget  &lt;NA&gt;      Budget required for all other budget line …
10 budget_patsup   Budget  &lt;NA&gt;      Budget required for patient support (US Do…
# ℹ 689 more rows</code></pre>
</div>
</div>
<p><strong>WHO MDR/RR-TB burden estimates:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading MDR/RR-TB burden estimates</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>data_file <span class="ot">&lt;-</span> <span class="st">&quot;01_load_MDR_RR_burden_estimates.tsv&quot;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="ot">&lt;-</span> <span class="fu">load_data</span>(data_file)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading ../data/01_load_MDR_RR_burden_estimates.tsv from local file…</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Display the data_</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mdr_rr_data</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,150 × 20
   country  iso2  iso3  iso_numeric g_whoregion  year source_rr_new e_rr_pct_new
   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt;
 1 Afghani… AF    AFG   004         EMR          2015 Surveillance           8.7
 2 Afghani… AF    AFG   004         EMR          2016 Surveillance           7.3
 3 Afghani… AF    AFG   004         EMR          2017 Surveillance           6  
 4 Afghani… AF    AFG   004         EMR          2018 Surveillance           5  
 5 Afghani… AF    AFG   004         EMR          2019 Surveillance           4.1
 6 Afghani… AF    AFG   004         EMR          2020 Surveillance           3.4
 7 Afghani… AF    AFG   004         EMR          2021 Surveillance           2.8
 8 Afghani… AF    AFG   004         EMR          2022 Surveillance           2.4
 9 Afghani… AF    AFG   004         EMR          2023 Surveillance           2  
10 Afghani… AF    AFG   004         EMR          2024 Surveillance           1.6
# ℹ 2,140 more rows
# ℹ 12 more variables: e_rr_pct_new_lo &lt;dbl&gt;, e_rr_pct_new_hi &lt;dbl&gt;,
#   source_rr_ret &lt;chr&gt;, e_rr_pct_ret &lt;dbl&gt;, e_rr_pct_ret_lo &lt;dbl&gt;,
#   e_rr_pct_ret_hi &lt;dbl&gt;, e_inc_rr_num &lt;dbl&gt;, e_inc_rr_num_lo &lt;dbl&gt;,
#   e_inc_rr_num_hi &lt;dbl&gt;, e_rr_in_notified_labconf_pulm &lt;dbl&gt;,
#   e_rr_in_notified_labconf_pulm_lo &lt;dbl&gt;,
#   e_rr_in_notified_labconf_pulm_hi &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>WHO Household contacts estimates:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading LTBI estimates (Household contacts) data:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>data_file   <span class="ot">&lt;-</span> <span class="st">&quot;01_load_LTBI_estimates.tsv&quot;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>ltbi_data <span class="ot">&lt;-</span> <span class="fu">load_data</span>(data_file)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading ../data/01_load_LTBI_estimates.tsv from local file…</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Display the data: </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ltbi_data</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,900 × 25
   country     iso2  iso3  iso_numeric g_whoregion  year source_hh     e_hh_size
   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
 1 Afghanistan AF    AFG   004         EMR          2015 DHS; 2015-10…      8.04
 2 Afghanistan AF    AFG   004         EMR          2016 DHS; 2015-10…      8.04
 3 Afghanistan AF    AFG   004         EMR          2017 DHS; 2015-10…      8.04
 4 Afghanistan AF    AFG   004         EMR          2018 DHS; 2015-10…      8.04
 5 Afghanistan AF    AFG   004         EMR          2019 DHS; 2015-10…      8.04
 6 Afghanistan AF    AFG   004         EMR          2020 DHS; 2015-10…      8.04
 7 Afghanistan AF    AFG   004         EMR          2021 DHS; 2015-10…      8.04
 8 Afghanistan AF    AFG   004         EMR          2022 DHS; 2015-10…      8.04
 9 Afghanistan AF    AFG   004         EMR          2023 DHS; 2015-10…      8.04
10 Afghanistan AF    AFG   004         EMR          2024 DHS; 2015-10…      8.04
# ℹ 1,890 more rows
# ℹ 17 more variables: prevtx_data_available &lt;dbl&gt;, newinc_con_prevtx &lt;dbl&gt;,
#   newinc_con04_prevtx &lt;dbl&gt;, ptsurvey_newinc &lt;dbl&gt;,
#   ptsurvey_newinc_con04_prevtx &lt;dbl&gt;, e_hh_contacts &lt;dbl&gt;,
#   e_hh_contacts_lo &lt;dbl&gt;, e_hh_contacts_hi &lt;dbl&gt;,
#   e_prevtx_hh_contacts_pct &lt;dbl&gt;, e_prevtx_hh_contacts_pct_lo &lt;dbl&gt;,
#   e_prevtx_hh_contacts_pct_hi &lt;dbl&gt;, e_prevtx_eligible &lt;dbl&gt;, …</code></pre>
</div>
</div>
<hr />
</section>
<section id="cleaning-the-4-datasets" class="level1">
<h1>Cleaning the 4 datasets</h1>
<section id="tb_burden-data-cleaning" class="level2">
<h2><strong>*TB_burden data cleaning:</strong></h2>
<p>Get only the data dictionary based on burden countries (and some extra) to understand the data on TB_burden and be able to properly clean it:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;iso3&#39;</span>,<span class="st">&#39;iso2&#39;</span>,<span class="st">&#39;iso_numeric&#39;</span>,<span class="st">&#39;g_whoregion&#39;</span>,<span class="st">&#39;year&#39;</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>TB_dictionary <span class="sc">|&gt;</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    variable_name <span class="sc">%in%</span> variables <span class="sc">|</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_starts</span>(variable_name, <span class="st">&#39;e_&#39;</span>) <span class="sc">|</span> </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_starts</span>(variable_name, <span class="st">&#39;cfr&#39;</span>) <span class="sc">|</span> </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_starts</span>(variable_name, <span class="st">&#39;c_&#39;</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 79 × 4
   variable_name dataset                code_list                     definition
   &lt;chr&gt;         &lt;chr&gt;                  &lt;chr&gt;                         &lt;chr&gt;     
 1 g_whoregion   Country identification AFR=Africa; AMR=Americas; EM… WHO region
 2 iso_numeric   Country identification &lt;NA&gt;                          ISO numer…
 3 iso2          Country identification &lt;NA&gt;                          ISO 2-cha…
 4 iso3          Country identification &lt;NA&gt;                          ISO 3-cha…
 5 c_cdr         Estimates              &lt;NA&gt;                          Case dete…
 6 c_cdr_hi      Estimates              &lt;NA&gt;                          Case dete…
 7 c_cdr_lo      Estimates              &lt;NA&gt;                          Case dete…
 8 c_newinc_100k Estimates              &lt;NA&gt;                          Case noti…
 9 cfr           Estimates              &lt;NA&gt;                          Estimated…
10 cfr_hi        Estimates              &lt;NA&gt;                          Estimated…
# ℹ 69 more rows</code></pre>
</div>
<div class="sourceCode" id="cb27"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The filter gets entries in the data dictonary where it either matches with </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#the &#39;variables&#39; vector, or where they start with &#39;e_&#39;, &#39;cfr&#39; or &#39;c_&#39;. </span></span></code></pre></div>
</div>
<p>Count nulls (NA) per column in TB_burden, and total amount of rows to compare them:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>na_counts <span class="ot">&lt;-</span> TB_burden <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;Column&quot;</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;NA_Count&quot;</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="sc">|&gt;</span> <span class="fu">count</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  5347</code></pre>
</div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>na_counts</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 2
   Column        NA_Count
   &lt;chr&gt;            &lt;int&gt;
 1 country              0
 2 iso2                25
 3 iso3                 0
 4 iso_numeric          0
 5 g_whoregion          0
 6 year                 0
 7 e_pop_num            0
 8 e_inc_100k          25
 9 e_inc_100k_lo       25
10 e_inc_100k_hi       25
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>Check the reason for missing values. For the cases with only 25 cases we can see it’s because of Namibia not having an iso2 country code, and also for North Korea not providing enough information.</p>
<p>For cases like e_tbhiv_prct_lo and e_tbhiv_prct_hi we see that the whole column is filled with NA’s. And finally there are some other columns with NA’s on some specific countries.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(iso2)) <span class="co">#Data from Namibia</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 50
   country iso2  iso3  iso_numeric g_whoregion  year e_pop_num e_inc_100k
   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 Namibia &lt;NA&gt;  NAM   516         AFR          2000   1818651        985
 2 Namibia &lt;NA&gt;  NAM   516         AFR          2001   1857048       1100
 3 Namibia &lt;NA&gt;  NAM   516         AFR          2002   1889967       1190
 4 Namibia &lt;NA&gt;  NAM   516         AFR          2003   1917455       1240
 5 Namibia &lt;NA&gt;  NAM   516         AFR          2004   1942083       1260
 6 Namibia &lt;NA&gt;  NAM   516         AFR          2005   1966573       1250
 7 Namibia &lt;NA&gt;  NAM   516         AFR          2006   1991890       1210
 8 Namibia &lt;NA&gt;  NAM   516         AFR          2007   2018595       1140
 9 Namibia &lt;NA&gt;  NAM   516         AFR          2008   2047048       1060
10 Namibia &lt;NA&gt;  NAM   516         AFR          2009   2077400        974
# ℹ 15 more rows
# ℹ 42 more variables: e_inc_100k_lo &lt;dbl&gt;, e_inc_100k_hi &lt;dbl&gt;,
#   e_inc_num &lt;dbl&gt;, e_inc_num_lo &lt;dbl&gt;, e_inc_num_hi &lt;dbl&gt;,
#   e_tbhiv_prct &lt;dbl&gt;, e_tbhiv_prct_lo &lt;lgl&gt;, e_tbhiv_prct_hi &lt;lgl&gt;,
#   e_inc_tbhiv_100k &lt;dbl&gt;, e_inc_tbhiv_100k_lo &lt;dbl&gt;,
#   e_inc_tbhiv_100k_hi &lt;dbl&gt;, e_inc_tbhiv_num &lt;dbl&gt;, e_inc_tbhiv_num_lo &lt;dbl&gt;,
#   e_inc_tbhiv_num_hi &lt;dbl&gt;, e_mort_exc_tbhiv_100k &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(e_inc_100k)) <span class="co">#Data from Korea</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 50
   country        iso2  iso3  iso_numeric g_whoregion  year e_pop_num e_inc_100k
   &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 Democratic Pe… KP    PRK   408         SEA          2000  23665911         NA
 2 Democratic Pe… KP    PRK   408         SEA          2001  23815359         NA
 3 Democratic Pe… KP    PRK   408         SEA          2002  23943979         NA
 4 Democratic Pe… KP    PRK   408         SEA          2003  24090380         NA
 5 Democratic Pe… KP    PRK   408         SEA          2004  24254941         NA
 6 Democratic Pe… KP    PRK   408         SEA          2005  24396437         NA
 7 Democratic Pe… KP    PRK   408         SEA          2006  24524508         NA
 8 Democratic Pe… KP    PRK   408         SEA          2007  24646381         NA
 9 Democratic Pe… KP    PRK   408         SEA          2008  24764617         NA
10 Democratic Pe… KP    PRK   408         SEA          2009  24878341         NA
# ℹ 15 more rows
# ℹ 42 more variables: e_inc_100k_lo &lt;dbl&gt;, e_inc_100k_hi &lt;dbl&gt;,
#   e_inc_num &lt;dbl&gt;, e_inc_num_lo &lt;dbl&gt;, e_inc_num_hi &lt;dbl&gt;,
#   e_tbhiv_prct &lt;dbl&gt;, e_tbhiv_prct_lo &lt;lgl&gt;, e_tbhiv_prct_hi &lt;lgl&gt;,
#   e_inc_tbhiv_100k &lt;dbl&gt;, e_inc_tbhiv_100k_lo &lt;dbl&gt;,
#   e_inc_tbhiv_100k_hi &lt;dbl&gt;, e_inc_tbhiv_num &lt;dbl&gt;, e_inc_tbhiv_num_lo &lt;dbl&gt;,
#   e_inc_tbhiv_num_hi &lt;dbl&gt;, e_mort_exc_tbhiv_100k &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(e_tbhiv_prct)) <span class="co">#Data for random columns</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 895 × 50
   country        iso2  iso3  iso_numeric g_whoregion  year e_pop_num e_inc_100k
   &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 American Samoa AS    ASM   016         WPR          2000     56851        5.3
 2 American Samoa AS    ASM   016         WPR          2001     57051        5.3
 3 American Samoa AS    ASM   016         WPR          2002     57053        3.5
 4 American Samoa AS    ASM   016         WPR          2003     56972        5.3
 5 American Samoa AS    ASM   016         WPR          2004     56817        8.8
 6 American Samoa AS    ASM   016         WPR          2005     56615       11  
 7 American Samoa AS    ASM   016         WPR          2006     56367        7.1
 8 American Samoa AS    ASM   016         WPR          2007     56115        5.3
 9 American Samoa AS    ASM   016         WPR          2008     55836        5.4
10 American Samoa AS    ASM   016         WPR          2009     55527        7.2
# ℹ 885 more rows
# ℹ 42 more variables: e_inc_100k_lo &lt;dbl&gt;, e_inc_100k_hi &lt;dbl&gt;,
#   e_inc_num &lt;dbl&gt;, e_inc_num_lo &lt;dbl&gt;, e_inc_num_hi &lt;dbl&gt;,
#   e_tbhiv_prct &lt;dbl&gt;, e_tbhiv_prct_lo &lt;lgl&gt;, e_tbhiv_prct_hi &lt;lgl&gt;,
#   e_inc_tbhiv_100k &lt;dbl&gt;, e_inc_tbhiv_100k_lo &lt;dbl&gt;,
#   e_inc_tbhiv_100k_hi &lt;dbl&gt;, e_inc_tbhiv_num &lt;dbl&gt;, e_inc_tbhiv_num_lo &lt;dbl&gt;,
#   e_inc_tbhiv_num_hi &lt;dbl&gt;, e_mort_exc_tbhiv_100k &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>As we have the iso3 country code, we don’t actually need an iso2, so we remove this column. Furthermore, we also remove iso3 and iso_numeric as they don’t provide any valuable information.</p>
<p>Also, as there are two columns that are full of missing values, in order to avoid using memory, and since they don’t give any information, we decided to remove them:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="ot">&lt;-</span> TB_burden <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>iso2, <span class="sc">-</span>iso3, <span class="sc">-</span>iso_numeric, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">-</span>e_tbhiv_prct_lo, <span class="sc">-</span>e_tbhiv_prct_hi)</span></code></pre></div>
</div>
<p>The “e” at the begining of the columns means “estimated” which is easy to understand.</p>
<p>But there are some problems as for example column “cfr_pct” refers to case fatality ratio percentage, though there are some other columns like “c_cdr” which are also expressed in terms of percentage as we can see when looking at the data dictionary. Therefore, those columns will be renamed for better understandably:</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>TB_burden_clean <span class="ot">&lt;-</span> TB_burden <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">c_cdr_pct =</span> c_cdr,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">c_cdr_pct_lo =</span> c_cdr_lo,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">c_cdr_pct_hi =</span> c_cdr_hi</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p>Show the first 50 rows of TB_burden_clean (sanity check):</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(TB_burden_clean,<span class="dv">50</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 45
   country    g_whoregion  year e_pop_num e_inc_100k e_inc_100k_lo e_inc_100k_hi
   &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
 1 Afghanist… EMR          2000  20130323        148            46          1510
 2 Afghanist… EMR          2001  20284311        175            66          1320
 3 Afghanist… EMR          2002  21378110        197            83          1140
 4 Afghanist… EMR          2003  22733047        215            97           992
 5 Afghanist… EMR          2004  23560660        228           109           862
 6 Afghanist… EMR          2005  24404569        237           118           754
 7 Afghanist… EMR          2006  25424099        242           124           662
 8 Afghanist… EMR          2007  25909852        241           127           597
 9 Afghanist… EMR          2008  26482615        235           127           559
10 Afghanist… EMR          2009  27466100        229           126           523
# ℹ 40 more rows
# ℹ 38 more variables: e_inc_num &lt;dbl&gt;, e_inc_num_lo &lt;dbl&gt;, e_inc_num_hi &lt;dbl&gt;,
#   e_tbhiv_prct &lt;dbl&gt;, e_inc_tbhiv_100k &lt;dbl&gt;, e_inc_tbhiv_100k_lo &lt;dbl&gt;,
#   e_inc_tbhiv_100k_hi &lt;dbl&gt;, e_inc_tbhiv_num &lt;dbl&gt;, e_inc_tbhiv_num_lo &lt;dbl&gt;,
#   e_inc_tbhiv_num_hi &lt;dbl&gt;, e_mort_exc_tbhiv_100k &lt;dbl&gt;,
#   e_mort_exc_tbhiv_100k_lo &lt;dbl&gt;, e_mort_exc_tbhiv_100k_hi &lt;dbl&gt;,
#   e_mort_exc_tbhiv_num &lt;dbl&gt;, e_mort_exc_tbhiv_num_lo &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Now we previously saw with a count() that there are 5347 rows, if we take in account that there are 25 years per country, then 5347/25 is not an integer. Therefore, we need to check which country or countries provided information from less years.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>TB_burden <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 2
    year     n
   &lt;dbl&gt; &lt;int&gt;
 1  2000   211
 2  2001   211
 3  2002   212
 4  2003   212
 5  2004   212
 6  2005   213
 7  2006   213
 8  2007   213
 9  2008   213
10  2009   213
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>As it can be see on year 2001 and 2001 there’s only have information from 211 countries, from 2002 to 2004 there are 212 countries, from 2005 to 2009 one more country, on 2010 a total of 214 countries and finally from 2011 a total of 215 countries.</p>
<p>This information is important to notice that this table alone can be used for certain statistics and graphs, though if there’s a need to join it with the other tables then it’s probably better to focus on year 2011 and onwards. Fortunately, the other two tables that can be used for a join have information only from 2015 and onwards.</p>
<p>So now we can save this table into our data folder which is already cleaned:</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Save data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">save_data</span>(TB_burden_clean, <span class="st">&quot;02_clean_TB_burden.tsv&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving ../data/02_clean_TB_burden.tsv to /data local file…</code></pre>
</div>
</div>
<hr />
</section>
<section id="tb_age_sex-data-cleaning" class="level2">
<h2><strong>*TB_age_sex data cleaning:</strong></h2>
<p><strong>Comments about the data:</strong></p>
<p>Shows estimated TB cases for different countries.</p>
<p>This particular dataset only contains data from <strong>2024</strong>.</p>
<p>Shows metadata about <strong>age</strong> groups, <strong>sex</strong>, and <strong>risk factors</strong> (e.g., HIV).</p>
<p>Furthermore, it shows the best estimate of TB cases (“<strong>best</strong>” column) a high bound of that estimate (“<strong>hi</strong>” column), and a lower bound of that estimate (“<strong>lo</strong>” column).</p>
<p><strong>Data exploration:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Some summary statistics: </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_rows =</span> <span class="fu">n</span>(),</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_countries =</span> <span class="fu">n_distinct</span>(country),</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_years =</span> <span class="fu">n_distinct</span>(year),</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_sex_categories =</span> <span class="fu">n_distinct</span>(sex),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_year =</span> <span class="fu">min</span>(year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_year =</span> <span class="fu">max</span>(year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cases_best =</span> <span class="fu">sum</span>(best, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cases_lo =</span> <span class="fu">sum</span>(lo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cases_hi =</span> <span class="fu">sum</span>(hi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
  n_rows n_countries n_years n_sex_categories min_year max_year total_cases_best
   &lt;int&gt;       &lt;int&gt;   &lt;int&gt;            &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;
1   9031         182       1                3     2024     2024         71744072
# ℹ 2 more variables: total_cases_lo &lt;dbl&gt;, total_cases_hi &lt;dbl&gt;</code></pre>
</div>
</div>
<p>9031 rows, 182 countries, 3 sex categories (male, female, and aggregated (aka. “both”)), a total estimate of 71,744,072 TB cases (<strong>~72 million TB cases in 2024</strong>).</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#All unique values in the &quot;measure&quot; column</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(measure)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  measure
  &lt;chr&gt;  
1 inc    </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#All unique values in the &quot;unit&quot; column</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(unit)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  unit 
  &lt;chr&gt;
1 num  </code></pre>
</div>
</div>
<p>“Unit = num” and “Measure = inc” mean that it is the number of TB incidences that year.</p>
<p><strong>Renaming columns in the data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Adjusting some of the column names, to make them more intuitive. </span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">iso_code =</span> iso3,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">TB_cases_best =</span> best,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">TB_cases_min =</span> lo,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">TB_cases_max =</span> hi</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(TB_age_sex, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 13
  country         iso2  iso_code iso_numeric  year measure unit  age_group sex  
  &lt;chr&gt;           &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;
1 Turkmenistan    TM    TKM      795          2024 inc     num   25-34     m    
2 Armenia         AM    ARM      051          2024 inc     num   35-44     m    
3 South Africa    ZA    ZAF      710          2024 inc     num   0-4       m    
4 Belarus         BY    BLR      112          2024 inc     num   0-4       m    
5 Lao People&#39;s D… LA    LAO      418          2024 inc     num   25-34     f    
# ℹ 4 more variables: risk_factor &lt;chr&gt;, TB_cases_best &lt;dbl&gt;,
#   TB_cases_min &lt;dbl&gt;, TB_cases_max &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Note: The age group sometimes contains info like “15plus” instead of e.g. “15-100” or “15+”.</p>
<p>Changing the sex: f, m, a to female, male, both (aggregated)</p>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The &#39;case_when()&#39; function is used to change the values. </span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co">#It works as a replace function. </span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">case_when</span>( </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>      sex <span class="sc">==</span> <span class="st">&quot;m&quot;</span> <span class="sc">~</span> <span class="st">&quot;Male&quot;</span>, </span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>      sex <span class="sc">==</span> <span class="st">&quot;f&quot;</span> <span class="sc">~</span> <span class="st">&quot;Female&quot;</span>, </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>      sex <span class="sc">==</span> <span class="st">&quot;a&quot;</span> <span class="sc">~</span> <span class="st">&quot;Both&quot;</span>, </span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(TB_age_sex, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 13
  country         iso2  iso_code iso_numeric  year measure unit  age_group sex  
  &lt;chr&gt;           &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;
1 Uzbekistan      UZ    UZB      860          2024 inc     num   55-64     Both 
2 Burundi         BI    BDI      108          2024 inc     num   15-24     Fema…
3 Algeria         DZ    DZA      012          2024 inc     num   15-19     Fema…
4 Sao Tome and P… ST    STP      678          2024 inc     num   all       Fema…
5 Madagascar      MG    MDG      450          2024 inc     num   15-19     Both 
# ℹ 4 more variables: risk_factor &lt;chr&gt;, TB_cases_best &lt;dbl&gt;,
#   TB_cases_min &lt;dbl&gt;, TB_cases_max &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sanity/ quality check: </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> <span class="fu">distinct</span>(sex)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  sex   
  &lt;chr&gt; 
1 Both  
2 Female
3 Male  </code></pre>
</div>
<div class="sourceCode" id="cb59"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Printing the unique values from the &quot;sex&quot; column</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co">#It should only return Male, Female and Both. </span></span></code></pre></div>
</div>
<p>Arguably, the columns for “iso2”, “iso_code”, iso_numeric”, “measure” and “unit” don’t present any particularly valuable info, so we will just remove those columns.</p>
<p><strong>Remove irrelevant columns:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb60"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">&quot;iso2&quot;</span>, <span class="sc">-</span><span class="st">&quot;iso_code&quot;</span>, </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">-</span><span class="st">&quot;iso_numeric&quot;</span>, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>         <span class="sc">-</span><span class="st">&quot;measure&quot;</span>, <span class="sc">-</span><span class="st">&quot;unit&quot;</span>) </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co">#The minus sign tells R to NOT select those columns. </span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(TB_age_sex, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  country  year age_group sex    risk_factor TB_cases_best TB_cases_min
  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;
1 Belgium  2024 65plus    Female all                    10            4
2 Kenya    2024 35-44     Male   all                 15000            0
3 Mali     2024 15plus    Female all                  4100          230
4 China    2024 25-34     Both   all                 68000        40000
5 Libya    2024 5-9       Male   all                    41            0
# ℹ 1 more variable: TB_cases_max &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>All of the risk factors in the data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> <span class="fu">distinct</span>(risk_factor)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  risk_factor
  &lt;chr&gt;      
1 all        
2 alc        
3 smk        
4 dia        
5 hiv        
6 und        </code></pre>
</div>
</div>
<p>all = no risk factor (“<em>not disaggregated by specific risk factors</em>”).</p>
<p>alc = alcoholism</p>
<p>smk = smoking</p>
<p>dia = diabetes</p>
<p>hiv = HIV infected</p>
<p>und = undernourishment</p>
<div class="cell">
<div class="sourceCode" id="cb65"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We can look up in the dictionary file to gain more insight: </span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>TB_dictionary <span class="sc">|&gt;</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dataset <span class="sc">==</span> <span class="st">&quot;Disaggregated estimates&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  variable_name dataset                 code_list                     definition
  &lt;chr&gt;         &lt;chr&gt;                   &lt;chr&gt;                         &lt;chr&gt;     
1 age_group     Disaggregated estimates 0-4=0-4 years; 5-14=5-14 yea… Age group…
2 best          Disaggregated estimates &lt;NA&gt;                          Best esti…
3 hi            Disaggregated estimates &lt;NA&gt;                          High boun…
4 lo            Disaggregated estimates &lt;NA&gt;                          Low bound…
5 measure       Disaggregated estimates inc = incidence               The measu…
6 risk_factor   Disaggregated estimates alc=Harmful use of alcohol; … Cases att…
7 sex           Disaggregated estimates a=All (females and males); f… Sex       
8 unit          Disaggregated estimates num=absolute number           The unit …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb67"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming the different risk factors: </span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> TB_age_sex <span class="sc">|&gt;</span> </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">risk_factor =</span> <span class="fu">case_when</span>( </span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;all&quot;</span> <span class="sc">~</span> <span class="st">&quot;no risk factor&quot;</span>, </span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;alc&quot;</span> <span class="sc">~</span> <span class="st">&quot;alcoholism&quot;</span>, </span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;smk&quot;</span> <span class="sc">~</span> <span class="st">&quot;smoking&quot;</span>, </span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;dia&quot;</span> <span class="sc">~</span> <span class="st">&quot;diabetes&quot;</span>, </span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;hiv&quot;</span> <span class="sc">~</span> <span class="st">&quot;HIV&quot;</span>, <span class="co">#capital letters</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>      risk_factor <span class="sc">==</span> <span class="st">&quot;und&quot;</span> <span class="sc">~</span> <span class="st">&quot;undernourishment&quot;</span> </span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div>
</div>
<p>Sanity check:</p>
<div class="cell">
<div class="sourceCode" id="cb68"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> <span class="fu">distinct</span>(risk_factor)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  risk_factor     
  &lt;chr&gt;           
1 no risk factor  
2 alcoholism      
3 smoking         
4 diabetes        
5 HIV             
6 undernourishment</code></pre>
</div>
</div>
<p><strong>Adjustments to age_group data:</strong></p>
<p>“15plus” should become “15+”.</p>
<div class="cell">
<div class="sourceCode" id="cb70"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> <span class="fu">distinct</span>(age_group)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 1
   age_group
   &lt;chr&gt;    
 1 0-14     
 2 0-4      
 3 10-14    
 4 15-19    
 5 15-24    
 6 15plus   
 7 18plus   
 8 20-24    
 9 25-34    
10 35-44    
11 45-54    
12 5-14     
13 5-9      
14 55-64    
15 65plus   
16 all      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb72"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="ot">&lt;-</span> TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">str_replace</span>(age_group, <span class="st">&quot;plus&quot;</span>, <span class="st">&quot;+&quot;</span>)) </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Replace &#39;plus&#39; with the actual sign. </span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb73"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sanity check: </span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span> <span class="fu">distinct</span>(age_group)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 1
   age_group
   &lt;chr&gt;    
 1 0-14     
 2 0-4      
 3 10-14    
 4 15-19    
 5 15-24    
 6 15+      
 7 18+      
 8 20-24    
 9 25-34    
10 35-44    
11 45-54    
12 5-14     
13 5-9      
14 55-64    
15 65+      
16 all      </code></pre>
</div>
</div>
<p><strong>Checking if there are any NA values in the data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb75"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking for NA values throughout entire dataset: </span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(TB_age_sex))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Could also have used this code to inspect each of the columns individually:</p>
<div class="cell">
<div class="sourceCode" id="cb77"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>            <span class="sc">~</span> <span class="fu">any</span>(<span class="fu">is.na</span>(.))))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  country year  age_group sex   risk_factor TB_cases_best TB_cases_min
  &lt;lgl&gt;   &lt;lgl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;       &lt;lgl&gt;         &lt;lgl&gt;       
1 FALSE   FALSE FALSE     FALSE FALSE       FALSE         FALSE       
# ℹ 1 more variable: TB_cases_max &lt;lgl&gt;</code></pre>
</div>
</div>
<p>As there are no further NA values, in the remaining, cleaned data, it seems fair to conclude the cleaning of the data here.</p>
<p><strong>Sample only the data from Denmark - quality check:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb79"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Denmark&quot;</span>, sex <span class="sc">==</span> <span class="st">&quot;Both&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 8
   country  year age_group sex   risk_factor      TB_cases_best TB_cases_min
   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;                    &lt;dbl&gt;        &lt;dbl&gt;
 1 Denmark  2024 0-14      Both  no risk factor              11            7
 2 Denmark  2024 0-4       Both  no risk factor               4            2
 3 Denmark  2024 10-14     Both  no risk factor               7            3
 4 Denmark  2024 15-19     Both  no risk factor               3            2
 5 Denmark  2024 15-24     Both  no risk factor              18           10
 6 Denmark  2024 15+       Both  alcoholism                  26           10
 7 Denmark  2024 15+       Both  no risk factor             180          140
 8 Denmark  2024 15+       Both  smoking                     15            4
 9 Denmark  2024 18+       Both  diabetes                     3            2
10 Denmark  2024 20-24     Both  no risk factor              14            7
11 Denmark  2024 25-34     Both  no risk factor              38           19
12 Denmark  2024 35-44     Both  no risk factor              32           16
13 Denmark  2024 45-54     Both  no risk factor              32           15
14 Denmark  2024 5-14      Both  no risk factor               7            3
15 Denmark  2024 5-9       Both  no risk factor               0            0
16 Denmark  2024 55-64     Both  no risk factor              28           13
17 Denmark  2024 65+       Both  no risk factor              33           17
18 Denmark  2024 all       Both  no risk factor             190          150
19 Denmark  2024 all       Both  HIV                          5            1
20 Denmark  2024 all       Both  undernourishment             4            2
# ℹ 1 more variable: TB_cases_max &lt;dbl&gt;</code></pre>
</div>
</div>
<p>(It is always nice to examine a subset where you have a realistic impression of the approximate number).</p>
<p>It is worth noting that (at least for Denmark) the risk factors are only reported on the “sex = Both” grouped data.</p>
<p>Based on the tibble above, it becomes clear that ‘risk factor = all’ might not be what we originally thought:</p>
<div class="cell">
<div class="sourceCode" id="cb81"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Understanding the &quot;all&quot; risk label: </span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Denmark&quot;</span>, risk_factor <span class="sc">!=</span> <span class="st">&quot;all&quot;</span>) <span class="sc">|&gt;</span> <span class="co">#The ones that are not labelled &quot;all&quot;. </span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_TB =</span> <span class="fu">sum</span>(TB_cases_best))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  sum_TB
   &lt;dbl&gt;
1   1247</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb83"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>TB_age_sex <span class="sc">|&gt;</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Denmark&quot;</span>, risk_factor <span class="sc">==</span> <span class="st">&quot;all&quot;</span>) <span class="sc">|&gt;</span> <span class="co">#The ones that ARE labelled &quot;all&quot;. </span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_TB =</span> <span class="fu">sum</span>(TB_cases_best))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  sum_TB
   &lt;dbl&gt;
1      0</code></pre>
</div>
</div>
<p><strong>Save the cleaned data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb85"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Save data</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">save_data</span>(TB_age_sex, <span class="st">&quot;02_clean_TB_age_sex.tsv&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving ../data/02_clean_TB_age_sex.tsv to /data local file…</code></pre>
</div>
</div>
<hr />
</section>
<section id="tb_household_estimates-data-cleaning" class="level2">
<h2><strong>*TB_household_estimates data cleaning:</strong></h2>
<div class="cell">
<div class="sourceCode" id="cb87"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>ltbi_data <span class="sc">|&gt;</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>() <span class="co">#Gives a compact overview of the tibble. </span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,900
Columns: 25
$ country                      &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanista…
$ iso2                         &lt;chr&gt; &quot;AF&quot;, &quot;AF&quot;, &quot;AF&quot;, &quot;AF&quot;, &quot;AF&quot;, &quot;AF&quot;, &quot;AF&quot;,…
$ iso3                         &lt;chr&gt; &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;,…
$ iso_numeric                  &lt;chr&gt; &quot;004&quot;, &quot;004&quot;, &quot;004&quot;, &quot;004&quot;, &quot;004&quot;, &quot;004&quot;,…
$ g_whoregion                  &lt;chr&gt; &quot;EMR&quot;, &quot;EMR&quot;, &quot;EMR&quot;, &quot;EMR&quot;, &quot;EMR&quot;, &quot;EMR&quot;,…
$ year                         &lt;dbl&gt; 2015, 2016, 2017, 2018, 2019, 2020, 2021,…
$ source_hh                    &lt;chr&gt; &quot;DHS; 2015-10-19&quot;, &quot;DHS; 2015-10-19&quot;, &quot;DH…
$ e_hh_size                    &lt;dbl&gt; 8.04, 8.04, 8.04, 8.04, 8.04, 8.04, 8.04,…
$ prevtx_data_available        &lt;dbl&gt; 60, 60, 60, 60, 60, 60, 60, 60, 1, 1, 60,…
$ newinc_con_prevtx            &lt;dbl&gt; NA, NA, NA, 22467, 24701, 23336, 25360, 3…
$ newinc_con04_prevtx          &lt;dbl&gt; 10164, 15417, 24666, 22467, 24701, 23336,…
$ ptsurvey_newinc              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ptsurvey_newinc_con04_prevtx &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ e_hh_contacts                &lt;dbl&gt; 120000, 130000, 140000, 140000, 170000, 1…
$ e_hh_contacts_lo             &lt;dbl&gt; 110000, 130000, 130000, 140000, 160000, 1…
$ e_hh_contacts_hi             &lt;dbl&gt; 120000, 130000, 140000, 150000, 170000, 1…
$ e_prevtx_hh_contacts_pct     &lt;dbl&gt; 8.70, 12.00, 35.00, 16.00, 15.00, 15.00, …
$ e_prevtx_hh_contacts_pct_lo  &lt;dbl&gt; 8.50, 12.00, 34.00, 15.00, 15.00, 15.00, …
$ e_prevtx_hh_contacts_pct_hi  &lt;dbl&gt; 8.90, 12.00, 35.00, 16.00, 15.00, 16.00, …
$ e_prevtx_eligible            &lt;dbl&gt; 22000.0, 24000.0, 25000.0, 26000.0, 30000…
$ e_prevtx_eligible_lo         &lt;dbl&gt; 20000.0, 22000.0, 23000.0, 24000.0, 27000…
$ e_prevtx_eligible_hi         &lt;dbl&gt; 24000.0, 26000.0, 28000.0, 29000.0, 33000…
$ e_prevtx_kids_pct            &lt;dbl&gt; 46.0, 64.0, 97.0, 85.0, 82.0, 85.0, 86.0,…
$ e_prevtx_kids_pct_lo         &lt;dbl&gt; 42.0, 58.0, 89.0, 78.0, 76.0, 78.0, 79.0,…
$ e_prevtx_kids_pct_hi         &lt;dbl&gt; 51, 70, 100, 93, 90, 93, 94, 100, 100, 10…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb89"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Cleaning the data - all-in-one: </span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>ltbi_data <span class="ot">&lt;-</span> ltbi_data <span class="sc">|&gt;</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Rename columns</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Contact Estimates</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Contacts_best         =</span> e_hh_contacts,</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Contacts_min          =</span> e_hh_contacts_lo,</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Contacts_max          =</span> e_hh_contacts_hi,</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preventive Treatment (General) </span></span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Pct     =</span> e_prevtx_hh_contacts_pct,</span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Pct_min =</span> e_prevtx_hh_contacts_pct_lo,</span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Pct_max =</span> e_prevtx_hh_contacts_pct_hi,</span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preventive Treatment (Eligibility) </span></span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Eligible     =</span> e_prevtx_eligible,</span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Eligible_min =</span> e_prevtx_eligible_lo,</span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Eligible_max =</span> e_prevtx_eligible_hi,</span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-21"><a href="#cb89-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preventive Treatment (Kids) </span></span>
<span id="cb89-22"><a href="#cb89-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Kids_Pct     =</span> e_prevtx_kids_pct,</span>
<span id="cb89-23"><a href="#cb89-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Kids_Pct_min =</span> e_prevtx_kids_pct_lo,</span>
<span id="cb89-24"><a href="#cb89-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Preventive_Tx_Kids_Pct_max =</span> e_prevtx_kids_pct_hi,</span>
<span id="cb89-25"><a href="#cb89-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb89-26"><a href="#cb89-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Metadata </span></span>
<span id="cb89-27"><a href="#cb89-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">WHO_region            =</span> g_whoregion</span>
<span id="cb89-28"><a href="#cb89-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb89-29"><a href="#cb89-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Remove irrelevant columns</span></span>
<span id="cb89-30"><a href="#cb89-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>iso2, <span class="sc">-</span>iso3, <span class="sc">-</span>iso_numeric,</span>
<span id="cb89-31"><a href="#cb89-31" aria-hidden="true" tabindex="-1"></a>          <span class="sc">-</span>newinc_con_prevtx, <span class="sc">-</span>newinc_con04_prevtx,</span>
<span id="cb89-32"><a href="#cb89-32" aria-hidden="true" tabindex="-1"></a>          <span class="sc">-</span>ptsurvey_newinc, <span class="sc">-</span>ptsurvey_newinc_con04_prevtx,</span>
<span id="cb89-33"><a href="#cb89-33" aria-hidden="true" tabindex="-1"></a>          <span class="sc">-</span>prevtx_data_available, <span class="sc">-</span>WHO_region) <span class="sc">|&gt;</span></span>
<span id="cb89-34"><a href="#cb89-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Clean survey source</span></span>
<span id="cb89-35"><a href="#cb89-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb89-36"><a href="#cb89-36" aria-hidden="true" tabindex="-1"></a>      <span class="at">survey_source =</span> <span class="fu">str_extract</span>(source_hh, <span class="st">&quot;^[^;]+&quot;</span>)</span>
<span id="cb89-37"><a href="#cb89-37" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb89-38"><a href="#cb89-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-39"><a href="#cb89-39" aria-hidden="true" tabindex="-1"></a><span class="co">#Check</span></span>
<span id="cb89-40"><a href="#cb89-40" aria-hidden="true" tabindex="-1"></a>ltbi_data <span class="sc">|&gt;</span> <span class="fu">summarise</span>(</span>
<span id="cb89-41"><a href="#cb89-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">min =</span> <span class="fu">min</span>(Preventive_Tx_Kids_Pct, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb89-42"><a href="#cb89-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="fu">max</span>(Preventive_Tx_Kids_Pct, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb89-43"><a href="#cb89-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(Preventive_Tx_Kids_Pct, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-44"><a href="#cb89-44" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
    min   max  mean
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0   100  56.1</code></pre>
</div>
<div class="sourceCode" id="cb91"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity check: View the updated column names</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ltbi_data)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] &quot;country&quot;                    &quot;year&quot;                      
 [3] &quot;source_hh&quot;                  &quot;e_hh_size&quot;                 
 [5] &quot;Contacts_best&quot;              &quot;Contacts_min&quot;              
 [7] &quot;Contacts_max&quot;               &quot;Preventive_Tx_Pct&quot;         
 [9] &quot;Preventive_Tx_Pct_min&quot;      &quot;Preventive_Tx_Pct_max&quot;     
[11] &quot;Preventive_Tx_Eligible&quot;     &quot;Preventive_Tx_Eligible_min&quot;
[13] &quot;Preventive_Tx_Eligible_max&quot; &quot;Preventive_Tx_Kids_Pct&quot;    
[15] &quot;Preventive_Tx_Kids_Pct_min&quot; &quot;Preventive_Tx_Kids_Pct_max&quot;
[17] &quot;survey_source&quot;             </code></pre>
</div>
</div>
<p><strong>Save the cleaned data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb93"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Save data</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">save_data</span>(ltbi_data, <span class="st">&quot;02_clean_LTBI_estimates.tsv&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving ../data/02_clean_LTBI_estimates.tsv to /data local file…</code></pre>
</div>
</div>
</section>
<section id="mdr_rr_tb_burden-data-cleaning" class="level2">
<h2><strong>*MDR_RR_TB_burden data cleaning :</strong></h2>
<p>Get the descriptions of the variables from the dictionary to understand what we are looking at:</p>
<div class="cell">
<div class="sourceCode" id="cb95"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>df_colnames <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">colname =</span> <span class="fu">colnames</span>(mdr_rr_data))</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>dict_filtered <span class="ot">&lt;-</span> </span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  TB_dictionary[<span class="fu">c</span>(<span class="st">&quot;variable_name&quot;</span>, <span class="st">&quot;definition&quot;</span>)] <span class="sc">|&gt;</span> </span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(variable_name <span class="sc">%in%</span> (df_colnames <span class="sc">|&gt;</span> </span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">pull</span>(colname)))</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>dict_filtered</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   variable_name                    definition                                  
   &lt;chr&gt;                            &lt;chr&gt;                                       
 1 country                          Country or territory name                   
 2 g_whoregion                      WHO region                                  
 3 iso_numeric                      ISO numeric country/territory code          
 4 iso2                             ISO 2-character country/territory code      
 5 iso3                             ISO 3-character country/territory code      
 6 e_inc_rr_num                     Estimated incidence of rifampicin resistant…
 7 e_inc_rr_num_hi                  Estimated incidence of rifampicin resistant…
 8 e_inc_rr_num_lo                  Estimated incidence of rifampicin resistant…
 9 e_rr_in_notified_labconf_pulm    Estimated number of RR-TB cases among notif…
10 e_rr_in_notified_labconf_pulm_hi Estimated number of RR-TB cases among notif…
11 e_rr_in_notified_labconf_pulm_lo Estimated number of RR-TB cases among notif…
12 e_rr_pct_new                     Estimated percentage of new TB cases with r…
13 e_rr_pct_new_hi                  Estimated percentage of new TB cases with r…
14 e_rr_pct_new_lo                  Estimated percentage of new TB cases with r…
15 e_rr_pct_ret                     Estimated percentage of previously treated …
16 e_rr_pct_ret_hi                  Estimated percentage of previously treated …
17 e_rr_pct_ret_lo                  Estimated percentage of previously treated …
18 source_rr_new                    Method used to estimate proportion of new T…
19 source_rr_ret                    Method used to estimate proportion of previ…</code></pre>
</div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>dict_missing <span class="ot">&lt;-</span> df_colnames <span class="sc">|&gt;</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>colname <span class="sc">%in%</span> (dict_filtered <span class="sc">|&gt;</span>  </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">pull</span>(variable_name)))</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>dict_missing</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  colname
  &lt;chr&gt;  
1 year   </code></pre>
</div>
</div>
<p>The dictionary covers all variables except year.<br />
<br />
</p>
<p>Renaming them to be more intuitive:</p>
<div class="cell">
<div class="sourceCode" id="cb99"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="ot">&lt;-</span> mdr_rr_data <span class="sc">|&gt;</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Estimated RR-TB incidence (absolute)</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_incidence =</span> e_inc_rr_num,</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_incidence_max =</span> e_inc_rr_num_hi,</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_incidence_min =</span> e_inc_rr_num_lo,</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Estimated RR-TB among lab-confirmed pulmonary TB</span></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_labconf_pulm =</span> e_rr_in_notified_labconf_pulm,</span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_labconf_pulm_max =</span> e_rr_in_notified_labconf_pulm_hi,</span>
<span id="cb99-12"><a href="#cb99-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_labconf_pulm_min =</span> e_rr_in_notified_labconf_pulm_lo,</span>
<span id="cb99-13"><a href="#cb99-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-14"><a href="#cb99-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># % of new TB cases</span></span>
<span id="cb99-15"><a href="#cb99-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_new =</span> e_rr_pct_new,</span>
<span id="cb99-16"><a href="#cb99-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_new_max =</span> e_rr_pct_new_hi,</span>
<span id="cb99-17"><a href="#cb99-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_new_min =</span> e_rr_pct_new_lo,</span>
<span id="cb99-18"><a href="#cb99-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-19"><a href="#cb99-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># % of previously treated cases with RR-TB</span></span>
<span id="cb99-20"><a href="#cb99-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_treated =</span> e_rr_pct_ret,</span>
<span id="cb99-21"><a href="#cb99-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_treated_max =</span> e_rr_pct_ret_hi,</span>
<span id="cb99-22"><a href="#cb99-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_treated_min =</span> e_rr_pct_ret_lo,</span>
<span id="cb99-23"><a href="#cb99-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-24"><a href="#cb99-24" aria-hidden="true" tabindex="-1"></a>    <span class="co">#method for new TB</span></span>
<span id="cb99-25"><a href="#cb99-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_method_new =</span> source_rr_new,</span>
<span id="cb99-26"><a href="#cb99-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb99-27"><a href="#cb99-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">#method for previously treated TB</span></span>
<span id="cb99-28"><a href="#cb99-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">rr_method_treat =</span> source_rr_ret</span>
<span id="cb99-29"><a href="#cb99-29" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p>What is the number of observations per year and per country?<br />
</p>
<div class="cell">
<div class="sourceCode" id="cb100"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> <span class="fu">count</span>(country)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 215 × 2
   country                 n
   &lt;chr&gt;               &lt;int&gt;
 1 Afghanistan            10
 2 Albania                10
 3 Algeria                10
 4 American Samoa         10
 5 Andorra                10
 6 Angola                 10
 7 Anguilla               10
 8 Antigua and Barbuda    10
 9 Argentina              10
10 Armenia                10
# ℹ 205 more rows</code></pre>
</div>
<div class="sourceCode" id="cb102"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> <span class="fu">count</span>(year)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
    year     n
   &lt;dbl&gt; &lt;int&gt;
 1  2015   215
 2  2016   215
 3  2017   215
 4  2018   215
 5  2019   215
 6  2020   215
 7  2021   215
 8  2022   215
 9  2023   215
10  2024   215</code></pre>
</div>
</div>
<p>We have 215 countries and 10 years, with 1 observation per year per country.<br />
<br />
</p>
<p><strong>Checking for missing values (NA):</strong></p>
<div class="cell">
<div class="sourceCode" id="cb104"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> </span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 20
  country  iso2  iso3 iso_numeric g_whoregion  year rr_method_new rr_new
    &lt;int&gt; &lt;int&gt; &lt;int&gt;       &lt;int&gt;       &lt;int&gt; &lt;int&gt;         &lt;int&gt;  &lt;int&gt;
1       0    10     0           0           0     0           330    330
# ℹ 12 more variables: rr_new_min &lt;int&gt;, rr_new_max &lt;int&gt;,
#   rr_method_treat &lt;int&gt;, rr_treated &lt;int&gt;, rr_treated_min &lt;int&gt;,
#   rr_treated_max &lt;int&gt;, rr_incidence &lt;int&gt;, rr_incidence_min &lt;int&gt;,
#   rr_incidence_max &lt;int&gt;, rr_labconf_pulm &lt;int&gt;, rr_labconf_pulm_min &lt;int&gt;,
#   rr_labconf_pulm_max &lt;int&gt;</code></pre>
</div>
</div>
<p>All estimated values have 330 or 345 missing values.<br />
</p>
<div class="cell">
<div class="sourceCode" id="cb106"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Inspecting the rows/ countries which are specifically missing values: </span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> </span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(iso2)) <span class="sc">|&gt;</span> </span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), is.na)) <span class="sc">|&gt;</span> </span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">20</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 20
   country        iso2  iso3  iso_numeric g_whoregion  year rr_method_new rr_new
   &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
 1 Tuvalu         TV    TUV   798         WPR          2020 &lt;NA&gt;            NA  
 2 Iceland        IS    ISL   352         EUR          2015 &lt;NA&gt;            NA  
 3 Saint Kitts a… KN    KNA   659         AMR          2022 &lt;NA&gt;            NA  
 4 Latvia         LV    LVA   428         EUR          2018 Surveillance     9.5
 5 Aruba          AW    ABW   533         AMR          2022 &lt;NA&gt;            NA  
 6 Saint Lucia    LC    LCA   662         AMR          2015 &lt;NA&gt;            NA  
 7 Seychelles     SC    SYC   690         AFR          2015 &lt;NA&gt;            NA  
 8 San Marino     SM    SMR   674         EUR          2022 &lt;NA&gt;            NA  
 9 Puerto Rico    PR    PRI   630         AMR          2024 Surveillance     2.5
10 Cook Islands   CK    COK   184         WPR          2015 &lt;NA&gt;            NA  
11 Seychelles     SC    SYC   690         AFR          2018 &lt;NA&gt;            NA  
12 Anguilla       AI    AIA   660         AMR          2023 &lt;NA&gt;            NA  
13 British Virgi… VG    VGB   092         AMR          2019 &lt;NA&gt;            NA  
14 Palau          PW    PLW   585         WPR          2015 &lt;NA&gt;            NA  
15 British Virgi… VG    VGB   092         AMR          2018 &lt;NA&gt;            NA  
16 Iceland        IS    ISL   352         EUR          2023 &lt;NA&gt;            NA  
17 Saint Lucia    LC    LCA   662         AMR          2022 &lt;NA&gt;            NA  
18 Barbados       BB    BRB   052         AMR          2024 &lt;NA&gt;            NA  
19 Dominica       DM    DMA   212         AMR          2024 &lt;NA&gt;            NA  
20 Turks and Cai… TC    TCA   796         AMR          2016 &lt;NA&gt;            NA  
# ℹ 12 more variables: rr_new_min &lt;dbl&gt;, rr_new_max &lt;dbl&gt;,
#   rr_method_treat &lt;chr&gt;, rr_treated &lt;dbl&gt;, rr_treated_min &lt;dbl&gt;,
#   rr_treated_max &lt;dbl&gt;, rr_incidence &lt;dbl&gt;, rr_incidence_min &lt;dbl&gt;,
#   rr_incidence_max &lt;dbl&gt;, rr_labconf_pulm &lt;dbl&gt;, rr_labconf_pulm_min &lt;dbl&gt;,
#   rr_labconf_pulm_max &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb108"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(iso2)) </span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 20
   country iso2  iso3  iso_numeric g_whoregion  year rr_method_new        rr_new
   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;
 1 Namibia &lt;NA&gt;  NAM   516         AFR          2015 Survey &amp; Surveillan…    5.1
 2 Namibia &lt;NA&gt;  NAM   516         AFR          2016 Survey &amp; Surveillan…    4.9
 3 Namibia &lt;NA&gt;  NAM   516         AFR          2017 Survey &amp; Surveillan…    4.8
 4 Namibia &lt;NA&gt;  NAM   516         AFR          2018 Survey &amp; Surveillan…    4.6
 5 Namibia &lt;NA&gt;  NAM   516         AFR          2019 Survey &amp; Surveillan…    4.5
 6 Namibia &lt;NA&gt;  NAM   516         AFR          2020 Survey &amp; Surveillan…    4.4
 7 Namibia &lt;NA&gt;  NAM   516         AFR          2021 Survey &amp; Surveillan…    4.2
 8 Namibia &lt;NA&gt;  NAM   516         AFR          2022 Survey &amp; Surveillan…    4.1
 9 Namibia &lt;NA&gt;  NAM   516         AFR          2023 Survey &amp; Surveillan…    4  
10 Namibia &lt;NA&gt;  NAM   516         AFR          2024 Survey &amp; Surveillan…    3.9
# ℹ 12 more variables: rr_new_min &lt;dbl&gt;, rr_new_max &lt;dbl&gt;,
#   rr_method_treat &lt;chr&gt;, rr_treated &lt;dbl&gt;, rr_treated_min &lt;dbl&gt;,
#   rr_treated_max &lt;dbl&gt;, rr_incidence &lt;dbl&gt;, rr_incidence_min &lt;dbl&gt;,
#   rr_incidence_max &lt;dbl&gt;, rr_labconf_pulm &lt;dbl&gt;, rr_labconf_pulm_min &lt;dbl&gt;,
#   rr_labconf_pulm_max &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Random observations are missing estimated values.<br />
Namibia is missing ‘iso2’.<br />
</p>
<p>Removing ‘iso2’ and other redundant variables as with other datasets:</p>
<div class="cell">
<div class="sourceCode" id="cb110"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Removing redundant columns</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="ot">&lt;-</span> mdr_rr_data <span class="sc">|&gt;</span> </span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>iso2, <span class="sc">-</span>iso3, <span class="sc">-</span>iso_numeric)</span></code></pre></div>
</div>
<p>Are there countries that are entirely missing estimated values for all observations?<br />
</p>
<div class="cell">
<div class="sourceCode" id="cb111"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>mdr_rr_data <span class="sc">|&gt;</span> </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">|&gt;</span> </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">all_missing =</span> <span class="fu">all</span>(<span class="fu">is.na</span>(rr_incidence))) <span class="sc">|&gt;</span> </span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(all_missing)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 2
   country                all_missing
   &lt;chr&gt;                  &lt;lgl&gt;      
 1 American Samoa         TRUE       
 2 Andorra                TRUE       
 3 Anguilla               TRUE       
 4 Antigua and Barbuda    TRUE       
 5 Aruba                  TRUE       
 6 Barbados               TRUE       
 7 Bermuda                TRUE       
 8 British Virgin Islands TRUE       
 9 Cayman Islands         TRUE       
10 Cook Islands           TRUE       
# ℹ 23 more rows</code></pre>
</div>
</div>
<p>33 out of 215 countries are missing all estimated variables.</p>
<p>This is worth noting for later.</p>
<p><strong>Save cleaned data:</strong></p>
<div class="cell">
<div class="sourceCode" id="cb113"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save_data</span>(mdr_rr_data, <span class="st">&quot;02_clean_MDR_RR_burden_estimates.tsv&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving ../data/02_clean_MDR_RR_burden_estimates.tsv to /data local file…</code></pre>
</div>
</div>
<hr />
<p>Next stop, data augmentation!</p>
</section>
</section>

</main>
<!-- /main column -->
<script id = "quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->

</body>

</html>
